### ISSUE TITLE
LoL Mastery Manager has stopped working...

### ISSUE THREAD

**Issue by xplosion330** [maxdeviant/lol-mastery-manager#42]
It's trying to grab new data from champion.gg and it says "LoL Mastery Manager has stopped working"

**Comment by J-a-n-n** [comment]
"Rito" changed their Static Data (AGAIN!!!) , i made some changes to reflect this newer structure , you can check my fork and try ... not fully tested yet (sorry) , i had flu :D

**Comment by jpm1993** [comment]
How would I be able to try the newer structure also feel better J-a-n-n

**Comment by J-a-n-n** [comment]
Riot have changed masteries.json in the last couple of patches , just download my fork, build and try ( copy that file in your program directory along with the new executable and you'll be ready to go )

**Comment by WalkingBest** [comment]
Hi I am a noob and do not understand :( how to fix this problem?

**Comment by p3dr4m** [comment]
how do you build a fork ?

**Comment by xplosion330** [comment]
System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=LoLMasteryManager
  StackTrace:
       at LoLMasteryManager.MasteryManager.SaveMasteryPages(List`1 masteryPages) in C:\Users\Ismail\Desktop\lol-mastery-manager-2.0.1\LoLMasteryManager\MasteryManager.vb:line 308
       at LoLMasteryManager.MasteryManager..ctor() in C:\Users\Ismail\Desktop\lol-mastery-manager-2.0.1\LoLMasteryManager\MasteryManager.vb:line 120
       at LoLMasteryManager.Main..ctor() in C:\Users\Ismail\Desktop\lol-mastery-manager-2.0.1\LoLMasteryManager\Main.vb:line 11
  InnerException: 


gettin this error

**Comment by survfate** [comment]
Hey @J-a-n-n, mind doing a pre-built version for us?

**Comment by platywompus** [comment]
FYI I was able to fix the bug and submitted a pull request. For now, I've published an unofficial fix on my fork, and I'll take it down once the official project is up to date: [https://github.com/platywompus/lol-mastery-manager/releases/tag/2.0.2x](https://github.com/platywompus/lol-mastery-manager/releases/tag/2.0.2x)
